import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white dark:bg-slate-800 md:bg-slate-50 md:dark:bg-slate-900 ${inter.className}`}>{children}</body>
    </html>
  )
}
